import 'dart:convert';
import 'package:desktopapp/model.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class Mainhome extends StatefulWidget {
  @override
  _MainhomeState createState() => _MainhomeState();
}

class _MainhomeState extends State<Mainhome> {
  List<Autogenerated> datas = [];
  Future<List<Autogenerated>> fetchdata() async {
    var urL =
        "https://script.google.com/macros/s/AKfycbwHX3ih0sJKA-A36xeToC4chDHgXbr7sCzu1HviWSJNKKM4LsTe3qhMfg/exec";
    var response = await http.get(Uri.parse(urL));
    List<Autogenerated> datas = [];
    if (response.statusCode == 200) {
      var datajson = jsonDecode(response.body);
      for (var i in datajson) {
        datas.add(Autogenerated.fromJson(i));
      }
    }
    return datas;
  }

  @override
  Widget build(BuildContext context) {
    // print(fetchdata());

    fetchdata().then((value) {
      setState(() {
        datas.addAll(value);
      });
    });
    return Container(
        child: ListView.builder(
      itemCount: datas.length,
      itemBuilder: (context, index) {
        return Column(children: [
          Text("${datas[index].distance}"),
          Text("${datas[index].flowmeter}"),
          Text("${datas[index].temperature}"),
          Text("${datas[index].humidity}")
        ]);
      },
    ));
  }
}
